sudo: required

services: 
  - docker

language: node_js

node_js: 
  - "11.7.0"

jdk:
  - oraclejdk8

before_install:
  - java -version
  - chmod +x .travis-deploy-heroku.sh
  - cd ./src/main/angularUI/
  - npm install
  - npm install -g @angular/cli

before_script:
  - cd ../../..
script:
  - mvn clean verify
  
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "7c8e9d44-1555-4db1-82f6-16352a824c66"
  app: spar-boot-angulardemo
  on:
    repo: mshuphiyan/spring-boot-web-angular

cache.directories:
  - /var/lib/docker
  - $HOME/.m2
  - web/node_modules