language: java
services: 
  - docker
jdk:
  - oraclejdk8
install:
  - npm install
  - npm install -g @angular/cli
deploy:
  provider: heroku
  api-key: 
    secure: "7c8e9d44-1555-4db1-82f6-16352a824c66"
  app: spar-boot-angulardemo